export const RECEIVE_SHOPES = 'RECEIVE_SHOPES';
export const RECEIVE_SHOPES_ERROR = 'RECEIVE_SHOPES_ERROR';

export const RECEIVE_USER_LOCATION = 'RECEIVE_USER_LOCATION';
export const RECEIVE_USER_LOCATION_ERROR = 'RECEIVE_USER_LOCATION_ERROR';

export const RECEIVE_SELECTED_DISTANCE = 'RECEIVE_SELECTED_DISTANCE';
export const RECEIVE_SELECTED_MASK_TYPE = 'RECEIVE_SELECTED_MASK_TYPE';
